version: "3.9"
services:
  mongo:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  api:
    container_name: gograph_api
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
    - "8080:8080"
    environment:
      DB_URI: mongodb://admin:password@mongo:27017
    depends_on:
      - mongo