// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/nebisin/gograph/db"
)

type AuthPayload struct {
	Token string   `json:"token"`
	User  *db.User `json:"user"`
}
