// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"go.mongodb.org/mongo-driver/bson/primitive"
)

type CreateTweetParams struct {
	Content  string             `json:"content"`
	AuthorID primitive.ObjectID `json:"authorId"`
}

type Tweet struct {
	ID        primitive.ObjectID `json:"id"`
	Content   string             `json:"content"`
	Author    *User              `json:"author"`
	CreatedAt time.Time          `json:"createdAt"`
	UpdatedAt time.Time          `json:"updatedAt"`
}

type UpdateTweetParams struct {
	Content string `json:"content"`
}

type User struct {
	ID        primitive.ObjectID `json:"id"`
	Email     string             `json:"email"`
	Password  string             `json:"password"`
	CreatedAt time.Time          `json:"createdAt"`
	UpdatedAt time.Time          `json:"updatedAt"`
}
